name: WoolBattle
version: '1.0-SNAPSHOT'
main: net.thevace.woolbattle.WoolBattle
api-version: '1.21'
commands:
  joinQueue:
    description: joins a queue
    usage: /joinQueue
  startGame:
    description: start the woolbattle game
    usage: /startGame
  getQueue:
    description: get all queues or the queue a player is in
    usage: /getQueue <Player>
  getPlayerWool:
    description: get your wool
    usage: /getPlayerWool
  createQueue:
    description: create a new Queue
    usage: /createQueue <team size>
    aliases:
      - cq
  listallplayers:
    description: list all registered player
    usage: /listallplayers
  getAllListeners:
    description: get a list of all registered Listeners
    usage: /getAllListeners
depend: [InventoryFramework]

